[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = "1.48.0"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "6930966aabf9b49fb6a0dc8b61076fa3f1abc298"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "6930966aabf9b49fb6a0dc8b61076fa3f1abc298"
package = "azalea-client"

[dependencies.common]
path = "../../common"