[package]
name = "flex-update-mc-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
tokio = "1.48.0"

[dependencies.azalea-protocol]
git = "https://github.com/azalea-rs/azalea"
rev = "6c110f2731c3893af397cc6a660f374ff705c99b"
package = "azalea-protocol"

[dependencies.azalea-client]
git = "https://github.com/azalea-rs/azalea"
rev = "6c110f2731c3893af397cc6a660f374ff705c99b"
package = "azalea-client"

[dependencies.common]
path = "../../common"